### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by mrpuzzler** [devtodev-analytics/android-sdk#1]
Version 1.12.2

Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lcom/devtodev/push/logic/DTDInstanceIDListenerService;
com.devtodev.push.a.d.a

Caused by java.lang.ClassNotFoundException
Didn't find class "com.devtodev.push.logic.DTDInstanceIDListenerService"

dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass (ClassLoader.java:511)
java.lang.ClassLoader.loadClass (ClassLoader.java:469)
com.devtodev.push.a.d.a (PushUtils.java:18) <!--- HERE
com.devtodev.push.a.d (PushClient.java:235)
com.devtodev.push.a.c (PushClient.java:228)
com.devtodev.push.a.<init> (PushClient.java:66)
com.devtodev.push.a.a (PushClient.java:50)
com.devtodev.core.logic.SDKClient.a (SDKClient.java:154)
com.devtodev.core.logic.SDKClient$21.run (SDKClient.java:181)
com.devtodev.core.logic.a.b.a (EventsQueue.java:27)
com.devtodev.core.logic.SDKClient.endSession (SDKClient.java:177)
com.devtodev.core.logic.a.a.b (DevToDevActivityLifecycleCallback.java:72)
com.devtodev.core.logic.a.a.onActivityStopped (DevToDevActivityLifecycleCallback.java:52)
android.app.Application.dispatchActivityStopped (Application.java:232)
android.app.Activity.onStop (Activity.java:1619)
android.app.NativeActivity.onStop (NativeActivity.java:235)

**Comment by Skazochnij** [comment]
Good afternoon! Do you use Firebase for push-notifications? 
Do you have dependency in you gradle build conig?
`implementation 'com.google.android.gms:play-services-gcm:15.0.0'`

Now we support the both GCM and FCM services for push-notifications, from future version 1.13 we exclude GCM support and 'play-services-gcm' dependency no longer required.

**Comment by mrpuzzler** [comment]
I don't have it. But I have
apply plugin: 'com.google.gms.google-services'

I follow your instruction at https://www.devtodev.com/help/39/devtodev_sdk_for_android_analytics_part_integration/

**Comment by Skazochnij** [comment]
Please add following line in your dependency section and say if that fix your problem.
`implementation 'com.google.android.gms:play-services-gcm:15.0.0'`

**Comment by jpoag** [comment]
Greetings!

`DevToDevActivityLifecycleCallback.java` is implementation of `ActivityLifecycleCallback`, a class that registers itself for activity events.

Normally, I would wrap calls to DevToDev plugin with try/catch blocks and handle the error in a way that's appropriate for the app.  But I can't do this directly because DevToDev is auto registered for lifecycle events.

Now, I could wrap my App's `super.OnStop()` call with try/catch, and that would catch the error, but that presents another problem:

Facebook, AppsFlyer, Tune, Firebase, Twitter, Google+, etc.. are all registered as `ActivityLifecycleCallback` for DeepLinking and Analytics reasons.  Depending on where it's at in the list, it could prevent these other plugins from receiving the `onStop` event.

For DevToDev to be a good citizen, it should capture any errors in `DevToDevActivityLifecycleCallback.java` and log them. 

Thanks!

**Comment by mrpuzzler** [comment]
I don't use gms, why do I need this lib? Any progress on this bug?

**Comment by Skazochnij** [comment]
We released new version of our sdk [[v1.13]](https://github.com/devtodev-analytics/android-sdk/releases/tag/v1.13)
GCM dependency no longer required
